### ISSUE TITLE
getting this crash with chest cavity 1.3.1

### ISSUE THREAD

**Issue by Nathan22211** [Tigereye504/chest-cavity-special-organs#1]
https://gist.github.com/Nathan22211/f57fec2a76c2335429c76c5a9fe1852c

from the looks of it, you changed something in chest cavity that broke this mod

**Comment by Tigereye504** [comment]
I was worried about this, I made some major changes to modify drops api and I haven't yet gotten to updating special organs or hellish materials in turn. An update to those will be out before the weekend is over, for now your best bet is to either roll back chest cavity or disable special organs.

**Comment by Tigereye504** [comment]
Update pushed. Have fun!
